version: "3"

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: passw0rd
    restart: always
    image: postgres:12
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://app_user:passw0rd@db/app_db
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
